# Change these first
owner: IntelliTect # Your GitHub organization or username, where this repository lives
repo: EssentialCSharp.Status # The name of this repository

sites:
  - name: EssentialCSharp
    url: https://essentialcsharp.com/
    assignees:
      - BenjaminMichaelis
      - Keboo
  - name: IntelliTect.com
    url: https://intellitect.com/

status-website:
  baseUrl: /EssentialCSharp.Status
  logoUrl: https://intellitect.com/wp-content/uploads/2019/07/IntelliTect_BlueBlack.png
  name: IntelliTect Status
  introTitle: "This status page monitors EssentialCSharp.com"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/IntelliTect/EssentialCSharp.Status).
  navbar:
    - title: Status
      href: /
    - title: EssentialCSharp
      href: https://essentialcsharp.com/
    - title: IntelliTect
      href: https://intellitect.com/

commitMessages:
  readmeContent: ":pencil: Update summary in README [skip ci]"
  summaryJson: ":card_file_box: Update status summary [skip ci]"
  graphsUpdate: ":bento: Update graphs [skip ci]"
  commitAuthorName: "intellitect-bot"
  commitAuthorEmail: "intellitect-ci@IntelliTect.com"
  
workflowSchedule:
  uptime: "*/5 * * * *"

i18n:
  footer: This page is [open source]($REPO). Powered by [IntelliTect](https://intellitect.com/)
