# Change these first
owner: EssentialCSharp # Your GitHub organization or username, where this repository lives
repo: EssentialCSharp.Status # The name of this repository

sites:
  - name: EssentialCSharp
    url: https://essentialcsharp.com/
    assignees:
      - BenjaminMichaelis
      - Keboo

status-website:
  baseUrl: /EssentialCSharp.Status
  logoUrl: https://essentialcsharp.com/favicon.ico
  name: EssentialC# Status
  introTitle: "This status page monitors EssentialCSharp.com"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/EssentialCSharp/EssentialCSharp.Status).
  navbar:
    - title: Status
      href: /
    - title: EssentialCSharp
      href: https://essentialcsharp.com/

commitMessages:
  readmeContent: ":pencil: Update summary in README [skip ci]"
  summaryJson: ":card_file_box: Update status summary [skip ci]"
  graphsUpdate: ":bento: Update graphs [skip ci]"
  commitAuthorName: "BenjaminMichaelisBot"
  commitAuthorEmail: "127451266+BenjaminMichaelisBot@users.noreply.github.com"
  
workflowSchedule:
  uptime: "*/5 * * * *"

i18n:
  footer: This page is [open source]($REPO). Powered by [Essential C#](https://essentialcsharp.com/)
